players = {
    "Junior": ["Junior", "Júnior", "JR"],
    "Giga": ["Giga", "Gigante", "Gigantinho"],
    "Wesley": ["Wesley"],
    "Jorge": ["Jorge"],
    "Pedro Cabeludo": ["Pedro", "Pedro Cabeludo"],
    "Dudu": ["Dudu"],
    "Marcelo": ["Marcelo"],
    "Garcez": ["Garcez"],
    "Ronimar": ["Ronimar", "Robimar"],
    "Chan": ["Chan", "Cham"],
    "Confiança": ["Confiança"],
    "Regufe": ["Regufe"],
    "Ricardo": ["Ricardo", "Ricardinho"],
    "Hulk": ["Hulk", "Márcio"],
    "Fabinho": ["Fabinho", "Fábio"],
    "Salvador": ["Salvador"],
    "Cadu": ["Cadu"],
    "Felipão": ["Felipão"],
    "Felipe": ["Felipe"],
    "Eric": ["Eric"],
    "Maurício": ["Maurício"],
    "Denis": ["Denis"],
    "Luis": ["Luis", "Luiz"],
    "Pedro": ["Pedro"],
    "Lima": ["Lima"],
    "Elmo": ["Elmo"],
    "Leandro Conv": ["Leandro Conv", "Leandro conv", "Leandro convidado"],
    "Paulo": ["Paulo", "Seu Paulo"],
    "Leonardo Conv": ["Leonardo Conv", "Leonardo conv", "Leonardo convidado"],
    "Wilton Conv": ["Wilton Conv", "Wilton conv", "Wilton convidado"],
    "Ruan": ["Ruan"],
    "Claudio": ["Claudio"],
    "Goleiro Gordo": ["Goleiro Gordo", "Gordo"],
    "Harison Conv": ["Harison Conv", "Harison conv", "Harison convidado"],
    "GB": ["GB"],
    "João": ["João", "João Goleiro", "João - Goleiro"],
    "Micha": ["Micha"],
    "Diogo Conv": ["Diogo Conv", "Diogo conv", "Diogo convidado", "Diogo C", "Diogo c"],
    "Mateus Conv": ["Mateus Conv", "Mateus conv", "Mateus convidado", "Mateus C", "Mateus c", "Matheus"],
    "Felipe Conv": ["Felipe Conv", "Felipe conv", "Felipe convidado", "Felipe C", "Felipe c"],
    "Michel Conv": ["Michel Conv", "Michel conv", "Michel convidado", "Michel C", "Michel c"],
    "Rafael Conv": ["Rafael Conv", "Rafael conv", "Rafael convidado", "Rafael C", "Rafael c"],
    "Patrick Conv": ["Patrick Conv", "Patrick conv", "Patrick convidado", "Patrick C", "Patrick c"],
    "Lucas": ["Lucas"],
    "Leandro": ["Leandro"],
    "Vicente": ["Vicente"],
    "Léo Negão": ["Léo Negão", "Léo negão", "Leo negao", "Léo Negao", "Leo Negão", "Léo negao"],
}
