players = {
    "Junior": ["Junior", "Júnior", "JR"],
    "Giga": ["Giga", "Gigante", "Gigantinho"],
    "Wesley": ["Wesley"],
    "Jorge": ["Jorge"],
    "Pedro Cabeludo": ["Pedro", "Pedro Cabeludo"],
    "Dudu": ["Dudu"],
    "Marcelo": ["Marcelo"],
    "Garcez": ["Garcez"],
    "Ronimar": ["Ronimar", "Robimar"],
    "Chan": ["Chan", "Cham"],
    "Confiança": ["Confiança", "Lucas"],
    "Regufe": ["Regufe"],
    "Ricardo": ["Ricardo", "Ricardinho"],
    "Hulk": ["Hulk", "Márcio"],
    "Fabinho": ["Fabinho", "Fábio"],
    "Salvador": ["Salvador"],
    "Cadu": ["Cadu"],
    "Felipão": ["Felipão", "Felipe"],
    "Eric": ["Eric"],
    "Maurício": ["Maurício"],
    "Denis": ["Denis"],
    "Luis": ["Luis", "Luiz"],
    "Pedro": ["Pedro"],
    "Lima": ["Lima"],
    "Elmo": ["Elmo"],
}
